# Generated by Django 4.2.13 on 2024-07-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_meals_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
