# Generated by Django 4.2.13 on 2024-07-04 08:58

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="blog/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 4, 8, 58, 20, 16333, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
