# Generated by Django 4.2.13 on 2024-07-05 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_tags_alter_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 7, 40, 10, 934518, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
