# Generated by Django 4.2.13 on 2024-07-05 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 8, 2, 55, 664515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
