# Generated by Django 4.2.13 on 2024-07-05 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_slug_alter_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 8, 18, 16, 343169, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
