# Generated by Django 4.2.13 on 2024-07-05 09:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_comment_options_alter_comment_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="user",),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="comment",
            name="phone",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 9, 15, 29, 112299, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
