# Generated by Django 4.2.13 on 2024-07-05 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_comment_user_comment_name_comment_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 9, 17, 12, 480813, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
