# Generated by Django 4.2.13 on 2024-07-05 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 9, 18, 36, 97120, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
