# Generated by Django 4.2.13 on 2024-07-05 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(default="Anonymous", max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 9, 25, 21, 386021, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
