# Generated by Django 4.2.13 on 2024-07-05 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_alter_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 15, 25, 40, 462873, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
