# Generated by Django 4.2.13 on 2024-07-07 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 7, 15, 5, 18, 367550, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
