# Generated by Django 4.2.13 on 2024-07-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "About Us", "verbose_name_plural": "About Us"},
        ),
        migrations.AlterModelOptions(
            name="chef",
            options={"verbose_name": "Chef", "verbose_name_plural": "Chef"},
        ),
        migrations.AlterModelOptions(
            name="why_choose_us",
            options={
                "verbose_name": "Why Choose Us",
                "verbose_name_plural": "Why Choose Us",
            },
        ),
    ]
